
# Site settings
title: MloVtry
email: 1150041224@qq.com 
description: >  同志，伏特加！[吨吨吨吨吨?]
  ---点火机打不着的酒还是不要拿上来了，那不好喝。＃描述
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/JekyllTheme-ProjectGaia" # the subpath of your site, e.g. /blog/
url: "https://MloVtry.github.io" # the base hostname & protocol for your site

# User setting
owner: MloVtry
email: Wanting-47156 
facebook_username: 2333 in China 
twitter_username: like up 
github_username: MloVtry
address:
  - line: 你以为 
  - line: 我会写 
  # Feel free to add more lines here 
telephone: 喵喵喵 
copyright: 喵喵喵？ 

# API settings
google_api_key:

# Build settings
gems: [jekyll-paginate]

markdown: kramdown
# toc_levels: 1..2
